#!/bin/bash
set -e

# Dynamic Port Configurations (Host Mode Compatibility)
Spokes_HOST_PORT=${Spokes_Host_Port:-8080}
VOICE_PORT=${Spokes_Voice_Port:-7880}
FALLBACK_PORT=${Spokes_Voice_Fallback_Port:-7881}

PORT_COUNT=${Spokes_VOICE_UDP_PORT_COUNT:-500}
START_PORT=${Spokes_Voice_UDP_Start_Port:-30000}
END_PORT=$((START_PORT + PORT_COUNT - 1))

# Dynamically set the .NET web server binding port
export ASPNETCORE_URLS="http://+:$Spokes_HOST_PORT"

# LiveKit config is dynamically generated by Spokes_Server during boot

# Check if Casdoor should be auto-started
DATA_DIR=${DataPath:-"/data"}
if [ -f "$DATA_DIR/casdoor.enabled" ]; then
    echo "Casdoor is enabled. Configuring Supervisor to autostart Casdoor."
    sed -i '/^\[program:casdoor\]/,/^\[/ s/^autostart=false/autostart=true/' /app/supervisord.conf

    echo "Restoring Casdoor configuration from persistent volume..."
    if [ -d "$DATA_DIR/casdoor/conf" ]; then
        cp -r $DATA_DIR/casdoor/conf/* /app/casdoor/conf/ 2>/dev/null || true
    fi
    if [ -f "$DATA_DIR/casdoor/init_data.json" ]; then
        cp $DATA_DIR/casdoor/init_data.json /app/casdoor/init_data.json 2>/dev/null || true
    fi
fi

echo "Starting Supervisord..."
exec /usr/bin/supervisord -c /app/supervisord.conf
